# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Mon Jun 25 02:24:14 2012
#      by: PyQt4 UI code generator 4.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_wolsettings(object):
    def setupUi(self, wolsettings):
        wolsettings.setObjectName(_fromUtf8("wolsettings"))
        wolsettings.setEnabled(True)
        wolsettings.resize(500, 200)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wolsettings.sizePolicy().hasHeightForWidth())
        wolsettings.setSizePolicy(sizePolicy)
        wolsettings.setMinimumSize(QtCore.QSize(400, 200))
        wolsettings.setMaximumSize(QtCore.QSize(500, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("res/setup.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        wolsettings.setWindowIcon(icon)
        wolsettings.setModal(True)
        self.horizontalLayout = QtGui.QHBoxLayout(wolsettings)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 16, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.newServer = QtGui.QPushButton(wolsettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newServer.sizePolicy().hasHeightForWidth())
        self.newServer.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("res/server-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newServer.setIcon(icon1)
        self.newServer.setObjectName(_fromUtf8("newServer"))
        self.horizontalLayout_3.addWidget(self.newServer)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.serversView = QtGui.QTreeView(wolsettings)
        self.serversView.setIndentation(0)
        self.serversView.setRootIsDecorated(False)
        self.serversView.setItemsExpandable(False)
        self.serversView.setObjectName(_fromUtf8("serversView"))
        self.verticalLayout.addWidget(self.serversView)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(wolsettings)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(22, 0))
        self.label_2.setMaximumSize(QtCore.QSize(22, 16777215))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.aliasText = QtGui.QLineEdit(self.groupBox)
        self.aliasText.setObjectName(_fromUtf8("aliasText"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.aliasText)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.macText = QtGui.QLineEdit(self.groupBox)
        self.macText.setInputMask(_fromUtf8(""))
        self.macText.setObjectName(_fromUtf8("macText"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.macText)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.portText = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portText.sizePolicy().hasHeightForWidth())
        self.portText.setSizePolicy(sizePolicy)
        self.portText.setMaximumSize(QtCore.QSize(48, 16777215))
        self.portText.setInputMask(_fromUtf8("00009; "))
        self.portText.setMaxLength(5)
        self.portText.setObjectName(_fromUtf8("portText"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.portText)
        self.asBroadcastCheck = QtGui.QCheckBox(self.groupBox)
        self.asBroadcastCheck.setEnabled(False)
        self.asBroadcastCheck.setCheckable(True)
        self.asBroadcastCheck.setChecked(True)
        self.asBroadcastCheck.setObjectName(_fromUtf8("asBroadcastCheck"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.asBroadcastCheck)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.wakeServer = QtGui.QPushButton(wolsettings)
        self.wakeServer.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("res/power.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wakeServer.setIcon(icon2)
        self.wakeServer.setObjectName(_fromUtf8("wakeServer"))
        self.horizontalLayout_2.addWidget(self.wakeServer)
        self.deleteServer = QtGui.QPushButton(wolsettings)
        self.deleteServer.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteServer.sizePolicy().hasHeightForWidth())
        self.deleteServer.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("res/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteServer.setIcon(icon3)
        self.deleteServer.setObjectName(_fromUtf8("deleteServer"))
        self.horizontalLayout_2.addWidget(self.deleteServer)
        self.saveServer = QtGui.QPushButton(wolsettings)
        self.saveServer.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveServer.sizePolicy().hasHeightForWidth())
        self.saveServer.setSizePolicy(sizePolicy)
        self.saveServer.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("res/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveServer.setIcon(icon4)
        self.saveServer.setObjectName(_fromUtf8("saveServer"))
        self.horizontalLayout_2.addWidget(self.saveServer)
        self.resetServer = QtGui.QPushButton(wolsettings)
        self.resetServer.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("res/reset.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetServer.setIcon(icon5)
        self.resetServer.setObjectName(_fromUtf8("resetServer"))
        self.horizontalLayout_2.addWidget(self.resetServer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(wolsettings)
        QtCore.QMetaObject.connectSlotsByName(wolsettings)

    def retranslateUi(self, wolsettings):
        wolsettings.setWindowTitle(QtGui.QApplication.translate("wolsettings", "Wake On LAN - Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.newServer.setText(QtGui.QApplication.translate("wolsettings", "Add a new server", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("wolsettings", "Server settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("wolsettings", "Alias", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("wolsettings", "MAC Address", None, QtGui.QApplication.UnicodeUTF8))
        self.macText.setPlaceholderText(QtGui.QApplication.translate("wolsettings", "00:00:00:00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("wolsettings", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.portText.setPlaceholderText(QtGui.QApplication.translate("wolsettings", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.asBroadcastCheck.setText(QtGui.QApplication.translate("wolsettings", "Send as broadcast", None, QtGui.QApplication.UnicodeUTF8))
        self.wakeServer.setText(QtGui.QApplication.translate("wolsettings", "Wake", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteServer.setText(QtGui.QApplication.translate("wolsettings", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.saveServer.setText(QtGui.QApplication.translate("wolsettings", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.resetServer.setText(QtGui.QApplication.translate("wolsettings", "Reset", None, QtGui.QApplication.UnicodeUTF8))

